### ISSUE TITLE
User Story: Model output evaluation

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr#101]
As a risk analyst, I would like to evaluate model outputs and trace back to model inputs for review and validation by inspecting metadata and previewing data using interactive maps.

Requires:
- documentation
- links to the assets
- interactive maps (i.e. Leaflet.js)

**Comment by drotheram** [comment]
https://github.com/OpenDRR/downloads
https://opendrr.github.io/downloads/
